name: Run tests

on: [ push, pull_request ]

jobs:
  build:
    # Run tests on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Checkout repo files
      - uses: actions/checkout@v3
      # Setup Python
      - uses: actions/setup-python@v3
        with:
          # Use latest version of Python 3
          python-version: 3.x

      - name: Run tests
        run: python3 Test.py
